### ISSUE TITLE
The timeout is limited to 10 seconds.

### ISSUE THREAD

**Issue by escudero** [atheriel/longears#19]
Hello,

The timeout is limited to 10 seconds.
Is this a limitation of RabbitMQ?
https://github.com/atheriel/longears/blob/2c1f841bc6c2decae77c94d03ec28d82abe8a0bf/src/consume.c#L137

Congratulations on the project.
Thanks

**Comment by atheriel** [comment]
I think you mean "60 seconds", not "10 seconds". This is intentional. To "wait forever" see my [comment](https://github.com/atheriel/longears/issues/8#issuecomment-699513434).
