### ISSUE TITLE
Publishing raw data

### ISSUE THREAD

**Issue by dselivanov** [atheriel/longears#3]
I'm trying to publish message which consist of raw data (in my case messagepack, but as an example i'm just sending byte encoded string). 

```r
library(longears)
con = amqp_connect()
msg = charToRaw("test")
amqp_publish(con, msg, exchange = "", routing_key = "test")
```
However somewhere internally it got encoded into "NA".

<img width="225" alt="Screen Shot 2020-02-04 at 19 50 39" src="https://user-images.githubusercontent.com/5123805/73761247-04ceaf80-4788-11ea-88e7-f4fb736d52e6.png">

**Comment by dselivanov** [comment]
Working in this - will submit PR soon.

**Comment by atheriel** [comment]
Yep, this is absolutely needed. I thought I'd implemented it long ago, but clearly that never got merged.
