### ISSUE TITLE
Issue compiling on Ubuntu against librabbitmq 0.4.1

### ISSUE THREAD

**Issue by Brendantales** [atheriel/longears#5]
Hi,

I am trying out to write rabbitmq producer and consumer in R.

When installing the longears package, I am facing the following issue
![image](https://user-images.githubusercontent.com/66125254/83265038-943c1a80-a1de-11ea-93f3-eb403d5edebf.png)

Is there any work around for this issue or is it due R version constraints? I am using R-3.3.1 in a very old machine, I am curious if that caused this issue

**Comment by atheriel** [comment]
What version of Ubuntu are you running and what version of `librabbitmq` is reported by the following?

```
$ apt show librabbitmq-dev
```

**Comment by Brendantales** [comment]
![image](https://user-images.githubusercontent.com/66125254/83400374-58909300-a420-11ea-8041-1fe9797dc19a.png)
It is shown this way. Sorry for late response. Thank you.

**Comment by Brendantales** [comment]
Sorry, please ignore the previous screenshot. That was from a different machine, this screenshot is the from the older machine, I am trying out
![image](https://user-images.githubusercontent.com/66125254/83404295-05224300-a428-11ea-89dc-f4aba811c04a.png)

**Comment by atheriel** [comment]
OK, I don't think I can support `0.4.1` of `librabbitmq` (which was released ~7 years ago), because the library has changed too much since then. I think we currently need `0.7.0` or later, possibly `0.6.0` could work.

You have two options:

1. Compile and install `librabbitmq` from source (which is here: https://github.com/alanxz/rabbitmq-c). It probably isn't as hard as you think.
2. Update to a newer version of Ubuntu, hopefully 16.04 or later.

**Comment by Brendantales** [comment]
Trying it on a new machine ubuntu 18.04, facing this issue now
![image](https://user-images.githubusercontent.com/66125254/83515483-0ec4ad00-a4f3-11ea-959a-b9f6294b3d09.png)

Here is the screenshot for running 'apt show librabbitmq-dev' command
![image](https://user-images.githubusercontent.com/66125254/83515625-4f242b00-a4f3-11ea-803c-05b214cd83a7.png)

**Comment by atheriel** [comment]
Thanks for your patience. This is related to your older R version, I think. Try the `master` branch to see if it has been resolved.

**Comment by Brendantales** [comment]
Thanks for the update. It is installed now on R-3.3.1
![image](https://user-images.githubusercontent.com/66125254/84154377-a6db0d00-aa84-11ea-8b9e-ca17d68c19c3.png)
Appreciate your support and timely responses.
